#!/bin/bash
# Chat simple — Utilitaire de consultation de discussion
# Lucien Guimier, 2014
#
# Ce programme est un logiciel libre ; vous pouvez le redistribuer ou le
# modifier suivant les termes de la WTFPL, version 2, telle que publiée
# par Sam Hocevar.
#
# Ce programme est distribué dans l’espoir qu’il sera utile, mais SANS
# AUCUNE GARANTIE, dans la limite de ce qui est autorisé par la loi. Il
# n’y a en particulier aucune garantie tacite de QUALITÉ MARCHANDE ou
# d’ADÉQUATION À UN BUT PARTICULIER.
#
# Vous devez avoir reçu une copie de la WTFPL en même temps que ce
# programme ; si ce n’est pas le cas, consultez <http://www.wtfpl.net/>.

##########
# Taper 'exit[Entrée]' permet de stopper l’exécution lorsque le script a été
# exécuté manuellement

IP="$( dirname "$( readlink --canonicalize "$0" )" )"
source "$IP/lib"

if $_sujet
then
	contenuSujet=`tail -n 1 "$sujet"`
	echo $_ui_titre$contenuSujet$_ui_defaut
	echo $_ui_ligne'------------------------------------------'$_ui_defaut
fi

tail -n $_precedentes -f "$canal" &

quitter=false

while ! $quitter
do
	read ligne
	if [ "$ligne" = 'exit' ]
	then
		quitter=true
	fi
done

tuerJobs
